---
#
# Ansible managed
#
repository:
  description: Install and configure mediawiki on your system.
  homepage: https://robertdebock.nl/
  topics: mediawiki, server, system, ansible, molecule, tox, playbook
