---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Connect to mediawiki
      ansible.builtin.get_url:
        url: http://localhost/mediawiki
        dest: /tmp/whatever
